const actions = {
    ADD_NEW_TASK: "ADD_NEW_TASK",
    INPUT_MUTATION_OBSERVER: "INPUT_MUTATION_OBSERVER",
    TEXTAREA_MUTATION_OBSERVER: "TEXTAREA_MUTATION_OBSERVER",
    CLEAR_ALL_THE_TASKS: "CLEAR_ALL_THE_TASKS",
    SELECT_TASK: "SELECT_TASK",
    DELETE_TASK: "DELETE_TASK",
}

export default actions;